services:
  # Our Flask App (The Ship)
  vessel-web:
    build: .
    environment:
      - DB_PASSWORD_FOR_PYTHON=${DB_PASS} # Passes it from the shell to Python
    ports:
      - "5000:5000"
    depends_on:
      - vessel-db
    networks:
      - port-network

  # Our Redis Database (The Logbook)
  vessel-db:
    image: redis:alpine
    command: redis-server --requirepass ${DB_PASS} --appendonly yes
    volumes:
      - ./redis_data:/data  # This is the "Anchor"
    networks:
      - port-network
  
  # --- THE OBSERVERS ---
  
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    networks:
      - port-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - port-network
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - port-network

networks:
  port-network:
    driver: bridge